### ISSUE TITLE
Improvement: i18n

### ISSUE THREAD

**Issue by alanmarcos** [ardakaracizmeli/design-system-checklist#1]
Can we do internationalization? I'm willing to do the pt-BR translation. Any idea on how so i can start a PR?

BTW, I'm loving this project! Already shared it across some ppl at my team and we're eager to start using!

**Comment by blvdmitry** [comment]
Hey, we definitely should do this! The more people we can reach - the better it is for the design and development communities.

I think the best place to start is to create a branch with a folder that replicates the structure of data files to make sure we take a content-first approach in this. Then we can come up with an implementation for switching the languages together.

Not for later: Probably there will be misalignments in terms of content in the future when can't get contributions fast enough to cover all the languages, so will need a design for that as well @ardakaracizmeli

**Comment by vicainelli** [comment]
Hey @alanmarcos  I willing to help with this

**Comment by ardakaracizmeli** [comment]
Human translated content would be ideal, but considering the scope and how inactive this issue is. I think it's safe to assume that people use Google Translate? Most of our users use the latest version of Chrome that has this enabled.

**Comment by blvdmitry** [comment]
@alanmarcos @vicainelli Hey folks, this is going to be solved by https://github.com/ardakaracizmeli/design-system-checklist/pull/31. So if you want to contribute the content for pt-BR, it's the time :)

**Comment by blvdmitry** [comment]
Merged now
