### ISSUE TITLE
Should Tooling be solution neutral?

### ISSUE THREAD

**Issue by sam-roberts** [ardakaracizmeli/design-system-checklist#12]
Hey big fan of the overall idea of this, one suggestion:
Under https://designsystemchecklist.com/category/tooling/ "Figma" is listed as checkbox. There are alternative tools out there to design teams such as Sketch, FramerX, AdobeXD and others. It shouldn't really matter which is used. At the moment it kind of reads like an advertisement Figma. 
Was just wondering the thinking behind this, and whether it could be reworded to be more neutral.

**Comment by blvdmitry** [comment]
Hey, originally it came from our current work experience so there is no intention to cover Figma only. We've discussed this on Twitter as well and it definitely should be reworded and provide more options than it currently has.

**Comment by modulareverything** [comment]
Yeah, it kind of feels like this is Figma-sponsored content with that plug. I'd be happy to do a PR with some potential changes here :)

**Comment by blvdmitry** [comment]
@chrish-d That would be great, we were discussing about naming it something like Vector design tool and moving Figma and other potential tools to the resources section
