### ISSUE TITLE
Improvement: Dark / Light theme selector

### ISSUE THREAD

**Issue by Marfru** [ardakaracizmeli/design-system-checklist#14]
Correct me if I'm wrong, but there's only dark theme right?

Would be nice to have light mode, especially during working hours, I prefer light mode.

Thanks!

**Comment by blvdmitry** [comment]
Hey, we change the theme based on the browser settings which should get the currently enabled mode from your OS settings. Therefore if you have dynamic light/dark mode enabled - I would expect it to switch automatically. Is this not happening?

**Comment by Marfru** [comment]
Oh very nice! Yeah it indeed works, just change my mac to Light Mode and its fine! Thanks, and good work!

#Closed
