### ISSUE TITLE
Feedback: Somewhat misleading link on About page

### ISSUE THREAD

**Issue by designorant** [ardakaracizmeli/design-system-checklist#2]
Not an issue, really, but since Design Systems are about uniformity and all that I'm sure I'm not the first one to notice that the last user handle link on [About page](https://designsystemchecklist.com/about/) is, rather surprisingly, a `mailto`:

> Hello, we're @ArdaKaracizmeli, @DmitryBelyaev and @StevenBaguley.

Great work btw! <3

**Comment by blvdmitry** [comment]
That's definitely surprising. @ardakaracizmeli let's ask Steven about any web page he wants to share instead or differentiate the link visually.

**Comment by ardakaracizmeli** [comment]
Thanks for the fair feedback @designorant. Glad you're enjoying it! I've changed Steven's handle to his LinkedIn profile as that was his preferred channel 🙌 

Closes with https://github.com/ardakaracizmeli/design-system-checklist/commit/d3582827572aac600505efaf6ad877ad8606fcb3.
