### ISSUE TITLE
Missing reference for best practise statement

### ISSUE THREAD

**Issue by sbhansen** [ardakaracizmeli/design-system-checklist#46]
Core / List / Divided variant states:
"Lists with dividers are the best practice advised by many platform guidelines (especially on mobile)."
I am unable to find the resources or sources that illustrates, verify or details this statement.
Checked: Material, Apple Human Interface Guidelines, Foundation, Bootstrap, Fluent, Equinor, DNB.

**Comment by blvdmitry** [comment]
Hey, I think we might be more specific about how many different types of lists can exist, and that's also the reason why it's hard to find that at first sight in other design systems. Here are a few examples:
- MUI: https://mui.com/material-ui/react-list/#align-list-items
- Chakra: https://chakra-ui.com/docs/components/stack/usage#stack-dividers
- Bootstrap: https://getbootstrap.com/docs/5.2/components/list-group/#basic-example
- Fluent: https://developer.microsoft.com/en-us/fluentui#/controls/web/list

What do you think will make this item more comprehensible for you?

**Comment by blvdmitry** [comment]
We've updated the content for the whole checklist now and this component was a part of the update
