### ISSUE TITLE
How can I open a PT-BR translation of the entire website? open a PR?

### ISSUE THREAD

**Issue by vitoriazoche** [ardakaracizmeli/design-system-checklist#48]
Hi!! I use and really like your checklist, but I don't know where to open this topic, I'm sorry if I open the discussion in the wrong environment.

I would like to contribute with the translation into Portuguese (Brazil)/PT-BR if possible.

**Comment by seahindeniz** [comment]
I guess you can just
- fork the repository
- duplicate a language folder 
- then edit the files on your own
- add the language code in the following line
  https://github.com/ardakaracizmeli/design-system-checklist/blob/59b09795a0aab34830eec54851e0ed1bba171b1b/next.config.js#L3

Here's the directory https://github.com/ardakaracizmeli/design-system-checklist/tree/master/src/translations

**Comment by blvdmitry** [comment]
Hey, sorry for a long answer. Yes, you can add a translation file same as they exist now. We've prepared the functionality for it quite some time ago but it never ended up getting the translation content. So feel free to open a PR with that and let us know if you need any help. 

One note is that we're working on v2 for the content right now - so it might be a better option to wait for that to get released first

**Comment by blvdmitry** [comment]
Just saw that there is a MR opened for the Portuguese: https://github.com/ardakaracizmeli/design-system-checklist/pull/49
Could you help with checking the content there? :)

**Comment by vitoriazoche** [comment]
wow, thanks for letting me know. I'll contribute with the guys over there

Em qui., 16 de mar. de 2023 às 17:35, Dmitry Belyaev <
***@***.***> escreveu:

**Comment by blvdmitry** [comment]
Since we've merge the PT translation now, feel free to open any additional pull requests if you think there are any improvements to be made. I'll close this issue for now, thanks for raising this!
