### ISSUE TITLE
Possible updates

### ISSUE THREAD

**Issue by lucasaugustsof** [ardakaracizmeli/design-system-checklist#65]
What do you think about evolving the project even further? Adding new patterns, updating dependencies, and more?

**Comment by blvdmitry** [comment]
Hey there, we've shipped a few major updates in the past and the most recent one still stand relevant today, so we're not planning anything new right now. We are happy to see others contributing, so if you have any ideas you want to see live feel free to start discussions or open pull requests 🙌

**Comment by lucasaugustsof** [comment]
Excellent!! I'm doing some studies and soon I'll be opening some PRs to analyze together :)
